run:
	export MKL_NUM_THREADS=4
	python BFChain.py 4 2
	export MKL_NUM_THREADS=3
	python BFChain.py 3 2
	export MKL_NUM_THREADS=2
	python BFChain.py 2 2
	export MKL_NUM_THREADS=1
	python BFChain.py 1 2
